global with sharing class AccountRemoter {

    public String accountName { get; set; }
    public static List<Account>  account { get; set; }
    public AccountRemoter() { } // empty constructor 
    
    
    @RemoteAction
    global static List<Account> getAccount(String accountName) {
        account = [SELECT Id, Name, Phone, Type, NumberOfEmployees 
                   FROM Account WHERE name = :accountname];
        return account;
    }
}